name = "medicalcalculator"
main = "src/worker.js"
compatibility_date = "2024-09-23"

# Bind the 'dist' directory to the ASSETS binding
# This allows the worker to serve the static files
[assets]
directory = "./dist"
binding = "ASSETS"
